name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Release Artifacts
        run: make release

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/*.yaml"
          generateReleaseNotes: true
          makeLatest: true

  docker:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          make docker-build-all
          make docker-push-all